# Generated by Django 5.0.6 on 2024-06-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeapp", "0002_recipe_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
