# Generated by Django 5.0.6 on 2024-06-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeapp", "0003_recipe_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="feedback",
            field=models.TextField(blank=True),
        ),
    ]
