# Generated by Django 5.0.6 on 2024-06-24 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeapp", "0004_recipe_feedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="likes",
        ),
        migrations.AddField(
            model_name="recipe",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_recipes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
