# Generated by Django 5.0.6 on 2024-06-25 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipeapp", "0007_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="is_read",
        ),
    ]
