# Generated by Django 5.0.6 on 2024-06-25 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeapp", "0008_remove_notification_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipeapp.recipe",
            ),
        ),
    ]
